name: Build frontend Docker container image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Github Packages authentication
      run: docker login docker.pkg.github.com -u MarkWme -p ${{ secrets.PACKAGES_TOKEN }} 
    - name: Build frontend Docker container image
      run: docker build ./src/frontend/ --tag docker.pkg.github.com/markwme/microservices-demo/frontend:$GITHUB_ACTION
    - name: Push image to GitHub packages
      run: docker push docker.pkg.github.com/markwme/microservices-demo/frontend:$GITHUB_ACTION
