name: Build frontend Docker container image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pwd
      run: pwd
    - name: ls
      run: ls . -al
    - name: Build frontend Docker container image
      run: docker build ./src/frontend/ --tag frontend:$(date +%s)
